#!/usr/bin/env node
/**
 * Legacy importer for the irdb CSV collection. The production catalogue is
 * generated by build-flipper-ir-db.mjs because that source includes captured
 * raw/stateful AC signals instead of only simple protocol/function tuples.
 *
 *   node scripts/build-ir-db.mjs /path/to/irdb-master/codes
 *
 * The output keeps only the protocols the app can encode on-device and only the
 * button names the on-screen remotes expose, which keeps the bundle small.
 */
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = process.argv[2];
if (!ROOT) {
  console.error("usage: build-ir-db.mjs <irdb codes dir>");
  process.exit(1);
}

const PROTOCOLS = new Map([
  ["NEC", "nec1"],
  ["NEC1", "nec1"],
  ["NEC2", "nec1"],
  ["NECx", "necx"],
  ["NECx1", "necx"],
  ["NECx2", "necx"],
  ["RC5", "rc5"],
  ["Sony12", "sony12"],
  ["Sony15", "sony15"],
  ["Sony20", "sony20"],
  ["Panasonic", "panasonic"],
  ["Panasonic2", "panasonic"],
  ["JVC", "jvc"],
]);

/** Appliance category for a device-type folder name. */
function category(deviceType) {
  const t = deviceType.toLowerCase();
  if (/(air condition|a\/c|aircon|heat pump)/.test(t)) return "ac";
  if (/fan/.test(t)) return "fan";
  if (/(projector)/.test(t)) return "projector";
  if (/(cable|satellite|satelite|set top|settop|dss|dth|tuner|dvr|iptv|hdtv)/.test(t)) return "stb";
  if (/(dvd|blu|vcr|laser disc|media player|media manager|recorder)/.test(t)) return "dvd";
  if (/(receiver|amplifier|audio|soundbar|sound bar|speaker|cd |mini system|karaoke|tape|tuner|home theat|jukebox|dsp|surround)/.test(t))
    return "audio";
  if (/(tv|plasma|lcd|led|monitor|display)/.test(t)) return "tv";
  return null;
}

const KEY_MAP = new Map(
  Object.entries({
    power: "power",
    key_power: "power",
    "power toggle": "power",
    "power on": "power",
    on: "power",
    key_power2: "power",
    "power off": "poweroff",
    off: "poweroff",
    standby: "poweroff",
    "volume +": "volup",
    "volume up": "volup",
    "vol +": "volup",
    "vol up": "volup",
    key_volumeup: "volup",
    "volume -": "voldown",
    "volume down": "voldown",
    "vol -": "voldown",
    "vol down": "voldown",
    key_volumedown: "voldown",
    mute: "mute",
    key_mute: "mute",
    "channel +": "chup",
    "channel up": "chup",
    "ch +": "chup",
    "ch up": "chup",
    key_channelup: "chup",
    "program +": "chup",
    "channel -": "chdown",
    "channel down": "chdown",
    "ch -": "chdown",
    "ch down": "chdown",
    key_channeldown: "chdown",
    "program -": "chdown",
    up: "up",
    "cursor up": "up",
    key_up: "up",
    "arrow up": "up",
    down: "down",
    "cursor down": "down",
    key_down: "down",
    "arrow down": "down",
    left: "left",
    "cursor left": "left",
    key_left: "left",
    right: "right",
    "cursor right": "right",
    key_right: "right",
    ok: "ok",
    select: "ok",
    enter: "ok",
    key_ok: "ok",
    key_enter: "ok",
    key_select: "ok",
    "cursor enter": "ok",
    back: "back",
    return: "back",
    key_back: "back",
    key_return: "back",
    "prev ch": "back",
    home: "home",
    key_home: "home",
    menu: "menu",
    key_menu: "menu",
    "main menu": "menu",
    exit: "exit",
    key_exit: "exit",
    cancel: "exit",
    guide: "guide",
    epg: "guide",
    key_epg: "guide",
    "tv guide": "guide",
    input: "input",
    "input source": "input",
    source: "input",
    "tv/video": "input",
    av: "input",
    key_video: "input",
    info: "info",
    display: "info",
    key_info: "info",
    play: "play",
    key_play: "play",
    pause: "pause",
    key_pause: "pause",
    "play/pause": "play",
    key_playpause: "play",
    stop: "stop",
    key_stop: "stop",
    next: "next",
    "skip >>": "next",
    key_next: "next",
    prev: "prev",
    previous: "prev",
    "skip <<": "prev",
    key_previous: "prev",
    rec: "rec",
    record: "rec",
    key_record: "rec",
    eject: "eject",
    "open/close": "eject",
    key_eject: "eject",
    key_ejectcd: "eject",
    rewind: "rew",
    key_rewind: "rew",
    "scan <<": "rew",
    "search <<": "rew",
    "fast forward": "ff",
    key_fastforward: "ff",
    key_forward: "ff",
    "scan >>": "ff",
    "search >>": "ff",
    sleep: "sleep",
    key_sleep: "sleep",
    subtitle: "subtitle",
    key_subtitle: "subtitle",
    audio: "audiotrack",
    key_audio: "audiotrack",
    red: "red",
    key_red: "red",
    green: "green",
    key_green: "green",
    yellow: "yellow",
    key_yellow: "yellow",
    blue: "blue",
    key_blue: "blue",
    "temperature +": "tempup",
    "temp +": "tempup",
    "temp up": "tempup",
    "temperature up": "tempup",
    "temperature -": "tempdown",
    "temp -": "tempdown",
    "temp down": "tempdown",
    "temperature down": "tempdown",
    mode: "mode",
    "fan speed": "fan",
    fan: "fan",
    swing: "swing",
    "swing up/down": "swing",
    timer: "timer",
    speed: "speed",
  }),
);

for (let d = 0; d <= 9; d++) {
  KEY_MAP.set(String(d), `d${d}`);
  KEY_MAP.set(`key_${d}`, `d${d}`);
  KEY_MAP.set(`digit ${d}`, `d${d}`);
  KEY_MAP.set(`num ${d}`, `d${d}`);
}

function normalizeKey(name) {
  const raw = name.trim().toLowerCase().replace(/\s+/g, " ");
  return KEY_MAP.get(raw) ?? null;
}

function listDirs(path) {
  return readdirSync(path).filter((entry) => {
    try {
      return statSync(join(path, entry)).isDirectory();
    } catch {
      return false;
    }
  });
}

/** category -> brand -> code sets */
const out = {};
let kept = 0;

for (const brand of listDirs(ROOT)) {
  if (/^unknown/i.test(brand)) continue;
  for (const deviceType of listDirs(join(ROOT, brand))) {
    const cat = category(deviceType);
    if (!cat) continue;
    const dir = join(ROOT, brand, deviceType);
    for (const file of readdirSync(dir)) {
      if (!file.endsWith(".csv")) continue;
      const rows = readFileSync(join(dir, file), "utf8").split(/\r?\n/).slice(1);
      let protocol = null;
      let device = 0;
      let sub = -1;
      const codes = {};
      for (const row of rows) {
        const cells = row.split(",");
        if (cells.length < 5) continue;
        const proto = PROTOCOLS.get(cells[1].trim());
        if (!proto) continue;
        const key = normalizeKey(cells[0]);
        if (!key) continue;
        const fn = Number(cells[4]);
        if (!Number.isFinite(fn)) continue;
        protocol = proto;
        device = Number(cells[2]) || 0;
        sub = Number(cells[3]);
        if (!Number.isFinite(sub)) sub = -1;
        if (codes[key] === undefined) codes[key] = fn;
      }
      // Needs enough working buttons to be worth listing.
      if (!protocol || Object.keys(codes).length < 3) continue;

      out[cat] ??= {};
      out[cat][brand] ??= [];
      out[cat][brand].push({ p: protocol, d: device, s: sub, k: codes });
      kept++;
    }
  }
}

// Sort brands, cap code sets per brand, drop duplicates.
const data = {};
for (const cat of Object.keys(out).sort()) {
  const brands = [];
  for (const name of Object.keys(out[cat]).sort((a, b) => a.localeCompare(b))) {
    const seen = new Set();
    const sets = [];
    for (const set of out[cat][name]) {
      const id = `${set.p}:${set.d}:${set.s}:${set.k.power ?? ""}`;
      if (seen.has(id)) continue;
      seen.add(id);
      sets.push(set);
      if (sets.length >= 12) break;
    }
    sets.sort((a, b) => Object.keys(b.k).length - Object.keys(a.k).length);
    brands.push({ n: name, r: sets });
  }
  data[cat] = brands;
}

writeFileSync("src/lib/ir-data.json", JSON.stringify(data));
const counts = Object.entries(data)
  .map(([cat, brands]) => `${cat}:${brands.length}b/${brands.reduce((n, b) => n + b.r.length, 0)}r`)
  .join(" ");
console.log(`kept ${kept} code sets -> ${counts}`);
